language: csharp
mono:
  - latest
  - 3.12.0
  - 3.10.0
  - 3.2.8
  - 2.10.8
solution: ThisData.Net.sln
script:
  - xbuild /p:Configuration=Release ThisData.Net.sln
  - mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./tests/bin/Release/ThisData.Net.Tests.dll